[package]
name = "near-jsonrpc-traits"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = true

[dependencies]
serde.workspace = true
serde_json.workspace = true

near-async.workspace = true
near-client.workspace = true
near-network.workspace = true
near-primitives.workspace = true
near-jsonrpc-primitives.workspace = true

[lints]
workspace = true

[features]
nightly = [
  "near-async/nightly",
  "near-client/nightly",
  "near-jsonrpc-primitives/nightly",
  "near-network/nightly",
  "near-primitives/nightly",
  "nightly_protocol",
]
nightly_protocol = [
  "near-async/nightly_protocol",
  "near-client/nightly_protocol",
  "near-jsonrpc-primitives/nightly_protocol",
  "near-network/nightly_protocol",
  "near-primitives/nightly_protocol",
]
